# Generated by Django 3.2.5 on 2021-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('category', models.CharField(choices=[('STD', 'Стандарт'), ('BSN', 'Бизнес'), ('LUX', 'Лукс'), ('ELUX', 'Ултра-лукс'), ('FAM', 'Фемили')], max_length=12)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.ImageField(default='room_thumbnails/t101.jpg', upload_to='room_thumbnails')),
            ],
        ),
    ]
