# Generated by Django 3.2.5 on 2021-07-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rate',
            new_name='price',
        ),
    ]
