# Generated by Django 3.2.5 on 2021-07-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('category', models.CharField(choices=[('STD', 'Стандарт'), ('BSN', 'Бизнес'), ('LUX', 'Лукс'), ('ELUX', 'Ултра-лукс'), ('FAM', 'Фемили')], max_length=12)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.ImageField(default='0.jpeg', upload_to='room_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активна'), ('finished', 'Завършена'), ('canceled', 'Отменена')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
